shapefilepath <- ("/Users/kayne/Documents/PGDip GIS/Geographic Data Science/Course Data/Session3&4 Data/Shapefiles/Camden_oa11.shp")
Shapefile <- st_read(shapefilepath)
plot(Shapefile)
OA.Census <- merge(Shapefile, practicaldata, by.x="OA11CD", by.y="OA")
OA.Census2 <- st_as_sf(OA.Census)
Model <- lm(Qualification ~ Unemployed + White_British, data = OA.Census2)
summary(Model)
OA.Census2$ModelRES <- residuals(Model)
plot(OA.Census2["ModelRES"], main = "Model Residual Values")
qtm(OA.Census2, "ModelRES") + tm_compass(type="arrow", position=c("left", "top"), show.labels = 1)
sf_data <- st_as_sf(OA.Census2, wkt="geometry")
sp_data <- as(sf_data, "Spatial")
GWRbandwidth <- gwr.sel(Qualification ~ Unemployed + White_British, data = sp_data, adapt = T)
GWRbandwidth
gwr.model = gwr(Qualification ~ Unemployed + White_British, data = sp_data, adapt=GWRbandwidth,
                hatmatrix = TRUE, se.fit= TRUE)
summary(gwr.model)
gwr.model
results <- as.data.frame(gwr.model$SDF)
gwr.map <- cbind(sp_data, as.matrix(results))
qtm(gwr.map, fill ="localR2") + tm_compass(type="arrow", position=c("left", "top"), show.labels = 1)
